apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-app
  namespace: taskmanager
  labels:
    app: taskmanager
spec:
  replicas: 2 # Run two instances for robustness
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: taskmanager-container
        # !! IMPORTANT: THIS TAG IS A PLACEHOLDER !!
        # Jenkins will replace this tag with the actual BUILD_NUMBER.
        image: akila1908/my-taskmanager-app:10
        ports:
        - containerPort: 3000
